### ISSUE TITLE
This isn't working!

### ISSUE THREAD

**Issue by djinnstar** [djinnstar/pyditya#1]
I'm getting math errors when I try to plot my functions. I have this great idea for trying to approximate a rectangle with a bunch of hills, but I can't seem to get the hill function to work!

**Comment by alags21** [comment]
Ok, sounds fun! I'll try and help.

**Comment by djinnstar** [comment]
Blah blah

**Comment by alags21** [comment]
yeet yeet

**Comment by djinnstar** [comment]
Here's what I'd like to do:

- [ ] Fix this silly bug. I mean, I can't even plot the functions in main.py right now!
- Feel free to switch the hill function to a parabola if you dislike semicircles.
- [ ] Decide whether to use parabolas or semicircles for the hill functions.
- [ ] Try plotting multiple hill functions added up together.
- [ ] Profit $$$.

@alags21 let me know when you've made some progress!

**Comment by djinnstar** [comment]
Awesome! This was resolved in pull request 1.
